---
version: "3"

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:edge
    container_name: audiobookshelf
    extends:
      file: docker-compose_base.yml
      service: base
    environment:
      AUDIOBOOKSHELF_UID: 99
      AUDIOBOOKSHELF_GID: 100
    ports:
      - 13378:80/tcp
    restart: unless-stopped
    volumes:
      - ~/Audiobooks:/audiobooks
      - ~/.config/audiobookshelf/config:/config
      - ~/.config/audiobookshelf/metadata:/metadata
      
  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - ~/.config/komga/config:/config
      - ~/Calibre Library:/data
      - /Volumes/Expansion/Media/Comics:/data2
    ports:
      - 8080:8080
    user: "1000:1000"
    restart: unless-stopped